"""update models

Revision ID: ae6dbae96923
Revises: 6342e15ecdac
Create Date: 2026-05-01 14:30:00.931701
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'ae6dbae96923'
down_revision = '6342e15ecdac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=False),
    sa.Column('compressed_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('specialist_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('compressed_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist.id'], name=op.f('specialist_images_specialist_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('specialist_images_pkey'))
    )
    op.drop_table('user_images')
    # ### end Alembic commands ###