"""update models

Revision ID: e8f5fca29c11
Revises: ae6dbae96923
Create Date: 2026-05-02 18:26:55.610546
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e8f5fca29c11'
down_revision = 'ae6dbae96923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accreditation_specialist_id_fkey'), 'accreditation', type_='foreignkey')
    op.create_foreign_key(None, 'accreditation', 'specialist', ['specialist_id'], ['id'])
    op.drop_constraint(op.f('address_user_id_fkey'), 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('audit_log_user_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('catalog_specialist_id_fkey'), 'catalog', type_='foreignkey')
    op.create_foreign_key(None, 'catalog', 'specialist', ['specialist_id'], ['id'])
    op.drop_constraint(op.f('comments_specialist_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'specialist', ['specialist_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(op.f('order_requests_specialist_id_fkey'), 'order_requests', type_='foreignkey')
    op.drop_constraint(op.f('order_requests_user_id_fkey'), 'order_requests', type_='foreignkey')
    op.create_foreign_key(None, 'order_requests', 'specialist', ['specialist_id'], ['id'])
    op.create_foreign_key(None, 'order_requests', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('rate_user_id_fkey'), 'rate', type_='foreignkey')
    op.drop_constraint(op.f('rate_specialist_id_fkey'), 'rate', type_='foreignkey')
    op.create_foreign_key(None, 'rate', 'specialist', ['specialist_id'], ['id'])
    op.create_foreign_key(None, 'rate', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('specialist_user_id_fkey'), 'specialist', type_='foreignkey')
    op.create_foreign_key(None, 'specialist', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_images_user_id_fkey'), 'user_images', type_='foreignkey')
    op.create_foreign_key(None, 'user_images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_images', type_='foreignkey')
    op.create_foreign_key(op.f('user_images_user_id_fkey'), 'user_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'specialist', type_='foreignkey')
    op.create_foreign_key(op.f('specialist_user_id_fkey'), 'specialist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rate', type_='foreignkey')
    op.drop_constraint(None, 'rate', type_='foreignkey')
    op.create_foreign_key(op.f('rate_specialist_id_fkey'), 'rate', 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('rate_user_id_fkey'), 'rate', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order_requests', type_='foreignkey')
    op.drop_constraint(None, 'order_requests', type_='foreignkey')
    op.create_foreign_key(op.f('order_requests_user_id_fkey'), 'order_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_requests_specialist_id_fkey'), 'order_requests', 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_specialist_id_fkey'), 'comments', 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.create_foreign_key(op.f('catalog_specialist_id_fkey'), 'catalog', 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_user_id_fkey'), 'audit_log', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key(op.f('address_user_id_fkey'), 'address', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'accreditation', type_='foreignkey')
    op.create_foreign_key(op.f('accreditation_specialist_id_fkey'), 'accreditation', 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###